namespace Domain.Constants;

public struct Strings
{
    public const string InvalidValue = "Geçersiz değer";
    public const string InvalidParameterCount = "Invalid parameter count";
    public const string IdNotEmpty = "Id girilmesi zorunludur.";
    public const string IdGreaterZero = "Id sıfırdan büyük olmalıdır.";
    public const string OperationContinues = "İşlem devam ediyor.";
    public const string UnsupportedFileFormat = "Geçersiz dosya tipi";
    public const string ExternalApiError = "Harici servis hatası";
    public const string ExternalApiBusy = "Harici servis meşgul";
    public const string Domain = "hamsterai.com.tr";
    public const string SwaggerPath = "/swagger";
    public const string XApiKey = "HaMsTerAI-Security";
    public const string AuthorizationDenied = "Bu işlem için yetkiniz bulunmamaktadır.";

    public const string DynamicNotEmpty = "{0} girilmesi zorunludur.";
    public const string DynamicMinLength = "{0} en az {1} karakter olmalıdır.";
    public const string DynamicMaxLength = "{0} en fazla {1} karakter olmalıdır.";
    public const string DynamicGratherThan = "{0} {1} büyük olmalıdır.";
    public const string DynamicGratherThanOrEquals = "{0} {1} büyük veya eşit olmalıdır.";
    public const string DynamicLessThan = "{0} {1} küçük olmalıdır.";
    public const string DynamicLessThanOrEquals = "{0} {1} küçük veya eşit olmalıdır.";
    public const string DynamicBetween = "{0} {1} - {2} arasında olmalıdır.";
    public const string DynamicOnlyDigit = "{0} sadece rakamlardan oluşmalıdır.";
    public const string DynamicNotFound = "{0} kaydı bulunamadı.";
    public const string DynamicNotFoundOrActive = "{0} kaydı bulunamadı veya aktif değil.";
    public const string DynamicExists = "{0} kaydı zaten mevcut.";
    public const string DynamicAdded = "{0} kayıt edildi.";
    public const string DynamicUpdated = "{0} kaydı güncellendi.";
    public const string DynamicPassived = "{0} kaydı pasif yapıldı.";
    public const string DynamicActived = "{0} kaydı aktif yapıldı.";
    public const string DynamicLessonQuestionAnswered = "{0} dersinin sorusu çözüldü.";
    public const string DynamicLessonQuestionPrepared = "{0} dersinin benzer sorusu hazırlandı.";

    public const string User = "Kullanıcı";
    public const string Name = "İsim";
    public const string OfName = "İsmi";
    public const string Name2 = "Ad";
    public const string OfName2 = "Adı";
    public const string Surname = "Soyisim";
    public const string City = "Şehir";
    public const string FoundationYear = "Kuruluş Yılı";
    public const string Website = "Websitesi";
    public const string UserName = "Kullanıcı Adı";
    public const string Password = "Şifre";
    public const string Phone = "Telefon";
    public const string OfPhone = "Telefonu";
    public const string PhoneNumber = "Telefon Numarası";
    public const string Email = "Email";
    public const string OfEmail = "Emaili";
    public const string UserType = "Kullanıcı Tipi";
    public const string School = "Okul";
    public const string Lesson = "Ders";
    public const string Question = "Soru";
    public const string SimilarQuestion = "Benzer Soru";
    public const string FileName = "Dosya adı";
    public const string TaxNumber = "Vergi Numarası";
    public const string Address = "Adres";
    public const string Şehir = "Şehir";
    public const string Authorized = "Yetkili";
    public const string Date = "Tarih";
    public const string OfDate = "Tarihi";
    public const string License = "Lisans";
    public const string LicenseEndDate = "Lisans Bitiş Tarihi";
    public const string UserCount = "Kullanıcı Sayısı";
    public const string SortNo = "Sıra No";
    public const string PasswordCode = "Şifre Kodu";
    public const string Answered = "Cevaplandı";
    public const string Prepared = "Hazırlandı";
    public const string Group = "Grup";
    public const string LessonGroup = "Ders Grubu";
    public const string SchoolName = "Okul Adı";
    public const string Token = "Token";
    public const string Title = "Ünvan";
    public const string Header = "Başlık";
    public const string Message = "Mesaj";

    public const string FileNameExtension = "Dosya adı içerisinde nokta olmalı ve uzantı belirtilmelidir.";

    public const string PasswordNumber = "Şifre içerisinde en az 1 adet sayı bulunmalıdır.";
    public const string PasswordLetter = "Şifre içerisinde en az 1 harf bulunmalıdır.";
    public const string UserNameSpace = "Kullanıcı adı boşluk içermemelidir.";
    public const string EmailWrongFormat = "Email bilgisi mail formatında olmalıdır.";

    public const string UserAssignClaimsNotNull = "Kullanıcı rolleri belirtilmelidir.";
    public const string UserDeniedEditForAdmin = "Admin kullanıcısının rolü değiştirilemez.";
    public const string UserAdminClaimNotAssign = "Admin rolü atanamaz.";
    public const string UserWrongRoles = "Rollerde yanlışlık var.";
    public const string UserOrPasswordNotWrong = "Kullanıcı adı veya şifre yanlış girildi.";
    public const string UserIsPassive = "Kullanıcı pasif durumdadır.";
    public const string InvalidRefreshTokenReuse = "İptal edilen üst token yeniden kullanılmaya çalışıldı.";
    public const string SessionTerminated = "Oturum sonlandırıldı.";
    public const string RevokeRefreshTokenLogout = "Çıkış yapılarak iptal edildi.";
    public const string ReplacedByNewToken = "Yeni tokenla değiştirildi.";
    public const string UserAssignScreensNotNull = "Kullanıcı ekranları belirtilmelidir.";
    public const string UserWrongScreens = "Ekran atamasında yanlışlık var.";
    public const string PasswordCodeExpired = "Şifre sıfırlama kodunun süresi doldu.";
    public const string UserTypeNotAllowed = "Kullanıcı tipine izin verilmiyor.";
    public const string UserDeniedPassiveForAdmin = "Admin kullanıcısı pasif yapılamaz.";

    public const string ModelBusy = "Model meşgul!";
}

//public const string _customerAdded = "Müşteri kayıt edildi.";
//public const string _customerUpdated = "Müşteri kaydı güncellendi.";
//public const string _customerPassived = "Müşteri kaydı pasif yapıldı.";
//public const string _customerActived = "Müşteri kaydı aktif yapıldı.";
//public const string _customerTitleNotEmpty = "Ünvan girilmesi zorunludur.";
//public const string _customerTitleMinimumLength = "Ünvan en az 5 karakter olmalıdır.";
//public const string _customerTitleMaximumLength = "Ünvan en fazla 127 karakter olmalıdır.";
//public const string _customerTaxOfficeNotEmpty = "Vergi dairesi girilmesi zorunludur.";
//public const string _customerTaxOfficeMinimumLength = "Vergi dairesi en az 5 karakter olmalıdır.";
//public const string _customerTaxOfficeMaximumLength = "Vergi dairesi en fazla 50 karakter olmalıdır.";
//public const string _customerTaxNumberNotEmpty = "Vergi numarası girilmesi zorunludur.";
//public const string _customerTaxNumberOnlyDigit = "Vergi numarası sadece rakam olmalıdır.";
//public const string _customerTaxNumberMinimumLength = "Vergi numarası en az 10 karakter olmalıdır.";
//public const string _customerTaxNumberMaximumLength = "Vergi numarası en fazla 11 karakter olmalıdır.";
//public const string _customerEmailWrongFormat = "Email bilgisi mail formatında olmalıdır.";
//public const string _customerEmailMinimumLength = "Email en az 6 karakter olmalıdır.";
//public const string _customerEmailMaximumLength = "Email en fazla 100 karakter olmalıdır.";
//public const string _customerPhoneOnlyDigit = "Telefon sadece rakam olmalıdır.";
//public const string _customerPhoneLength = "Telefon 10 karakter olmalıdır.";
//public const string _customerMikroCodeMaximumLength = "Mikro kodu en fazla 25 karakter olmalıdır.";
//public const string _customerNotFound = "Müşteri kaydı bulunamadı.";
//public const string _customerNotFoundActive = "Müşteri kaydı bulunamadı veya aktif değil";
//public const string _customerExistsTitle = "Ünvan mevcut. Pasif durumda olabilir.";
//public const string _customerExistsTaxNumber = "Vergi No mevcut. Pasif durumda olabilir.";
//public const string _customerExistsEmail = "Email mevcut. Pasif durumda olabilir.";
//public const string _customerExistsPhone = "Telefon mevcut. Pasif durumda olabilir.";
//public const string _customerExistsMikroCode = "Mikro kodu mevcut. Pasif durumda olabilir.";

//public const string _inventoryAdded = "Envanter kayıt edildi.";
//public const string _inventoryUpdated = "Envanter kaydı güncellendi.";
//public const string _inventoryPassived = "Envanter kaydı pasif yapıldı.";
//public const string _inventoryActived = "Envanter kaydı aktif yapıldı.";
//public const string _inventoryNameNotEmpty = "Envanter adı girilmesi zorunludur.";
//public const string _inventoryNameMinimumLength = "Envanter adı en az 2 karakter olmalıdır.";
//public const string _inventoryNameMaximumLength = "Envanter adı en fazla 50 karakter olmalıdır.";
//public const string _inventoryNotFound = "Envanter kaydı bulunamadı.";
//public const string _inventoryNotFoundActive = "Envanter kaydı bulunamadı veya aktif değil";
//public const string _inventoryExistsName = "Envanter adı mevcut. Pasif durumda olabilir.";

//public const string _inventoryInfoAdded = "Envanter bilgisi kayıt edildi.";
//public const string _inventoryInfoUpdated = "Envanter bilgisi güncellendi.";
//public const string _inventoryInfoPassived = "Envanter bilgisi pasif yapıldı.";
//public const string _inventoryInfoActived = "Envanter bilgisi aktif yapıldı.";
//public const string _inventoryInfoNameNotEmpty = "Envanter bilgisi adı girilmesi zorunludur.";
//public const string _inventoryInfoNameMinimumLength = "Envanter bilgisi adı en az 2 karakter olmalıdır.";
//public const string _inventoryInfoNameMaximumLength = "Envanter bilgisi adı en fazla 50 karakter olmalıdır.";
//public const string _inventoryInfoNotFound = "Envanter bilgisi kaydı bulunamadı.";
//public const string _inventoryInfoNotFoundActive = "Envanter bilgisi kaydı bulunamadı veya aktif değil";
//public const string _inventoryInfoExistsName = "Envanter bilgisi mevcut. Pasif durumda olabilir.";

//public const string _customerInventoryBrandMinimumLength = "Marka en az 2 karakter olmalıdır.";
//public const string _customerInventoryBrandMaximumLength = "Marka en fazla 50 karakter olmalıdır.";
//public const string _customerInventoryModelMinimumLength = "Model en az 2 karakter olmalıdır.";
//public const string _customerInventoryModelMaximumLength = "Model en fazla 50 karakter olmalıdır.";

//public const string _customerInventoryInfoValueNotEmpty = "Envanter verisi girilmesi zorunludur.";
//public const string _customerInventoryInfoValueMinimumLength = "Envanter verisi en az 1 karakter olmalıdır.";
//public const string _customerInventoryInfoValueMaximumLength = "Envanter verisi en fazla 250 karakter olmalıdır.";
//public const string _employeeEmailWrongFormat = "Email bilgisi mail formatında olmalıdır.";
//public const string _employeeEmailMinimumLength = "Email en az 6 karakter olmalıdır.";
//public const string _employeeEmailMaximumLength = "Email en fazla 100 karakter olmalıdır.";
//public const string _employeeMobileOnlyDigit = "Cep telefonu sadece rakam olmalıdır.";
//public const string _employeeMobileLength = "Cep telefonu 10 karakter olmalıdır.";
//public const string _employeeNotFound = "Personel kaydı bulunamadı.";
//public const string _employeeNotFoundActive = "Personel kaydı bulunamadı veya aktif değil";
//public const string _employeeExistsEmail = "Email mevcut. Pasif durumda olabilir.";
//public const string _employeeExistsMobile = "Cep telefonu mevcut. Pasif durumda olabilir.";
//public const string _employeeDeniedEditForOwnRecord = "Personel kendi kaydını değiştiremez.";

//public const string _employeeeAdded = "Personel kayıt edildi.";
//public const string _employeeUpdated = "Personel kaydı güncellendi.";
//public const string _employeePassived = "Personel kaydı pasif yapıldı.";
//public const string _employeeActived = "Personel kaydı aktif yapıldı.";

//public const string _userAdd = "Kullanıcı kayıt edildi.";
//public const string _userPasswordChanged = "Kullanıcı şifresi değiştirildi.";
//public const string _userAssignClaim = "Kullanıcı yetkisi güncellendi.";
//public const string _userPassive = "Kullanıcı kaydı pasif yapıldı.";
//public const string _userActive = "Kullanıcı kaydı aktif yapıldı.";
//public const string _userPasswordMinimumCharacter = "Şifre en az 8 karakter olmalıdır.";
//public const string _userPasswordNumber = "Şifre içerisinde en az 1 adet sayı bulunmalıdır.";
//public const string _userPasswordLetter = "Şifre içerisinde en az 1 harf bulunmalıdır.";
//public const string _userPasswordChangeHimSelf = "Sadece oturum açan kullanıcı hesabın şifresi değiştirilebilir.";
//public const string _ipAddressNotEmpty = "Ip adresi boş olamaz.";
//public const string _refreshTokenNotFound = "Yenileme tokenı bulunamadı.";
//public const string _invalidRefreshToken = "Geçersiz yenileme tokenı.";

//public const string _priorityMinimumValue = "Sıra numarası sıfırdan büyük olmalıdır.";
//public const string _priorityUpdate = "Sıra numarası güncellendi.";