name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.10

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  android_id: ^0.4.0
  animated_splash_screen: ^1.3.0
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0
  camera: ^0.10.0
  connectivity_plus: ^6.0.5
  crop_your_image: ^1.1.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.2
  dio: ^5.6.0
  email_validator: ^3.0.0
  firebase_analytics: ^11.3.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.2
  flutter_media_downloader: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_tex: ^4.0.9
  flutter_tts: ^4.0.2
  fluttertoast: ^8.2.8
  get: ^4.6.6
  image: ^4.3.0
  image_cropper: ^1.0.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  lottie: ^3.1.2
  mailer: ^6.3.0
  open_file: ^3.5.8
  path: ^1.9.0
  path_provider: ^2.0.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  quickalert: ^1.1.0
  shared_preferences: ^2.3.2
  syncfusion_flutter_pdfviewer: ^27.1.52
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/seduss_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FC8D19" # Arka plan rengi
  adaptive_icon_foreground: "assets/images/seduss_logo.png" # Ön plan
  remove_alpha_ios: true
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/email.svg
    - assets/images/Hamster.png
    - assets/images/hamster_only_logo.png
    - assets/images/seduss-soru-coz-logo.png
    - assets/icons/lock.svg
    - assets/icons/eye-on.svg
    - assets/icons/person_raised_hand.svg
    - assets/icons/crisis_alert.svg
    - assets/icons/psychology_alt.svg
    - assets/icons/Category.svg
    - assets/icons/Buy.svg
    - assets/icons/Scan.svg
    - assets/icons/Notification.svg
    - assets/icons/Profile.svg
    - assets/icons/backbutton.svg
    - assets/icons/settings.svg
    - assets/icons/gallery.svg
    - assets/icons/person.svg
    - assets/icons/edit.svg
    - assets/icons/lock2.svg
    - assets/icons/logout.svg
    - assets/icons/notiSettings.svg
    - assets/icons/edit_icon.svg
    - assets/icons/arrow.svg
    - assets/icons/lock_icon.svg
    - assets/icons/noti_icon.svg
    - assets/icons/logout_icon.svg
    - assets/icons/areusure.svg
    - assets/icons/tik.svg
    - assets/icons/threedot.svg
    - assets/icons/hamster_icon.svg
    - assets/icons/listen.svg
    - assets/images/question_ready.jpeg
    - assets/icons/bell.svg
    - assets/icons/loading_icon.svg
    - assets/images/loading_hamster.png
    - assets/images/hamster-logo.png
    - assets/icons/close.svg
    - assets/icons/checklist_rtl.svg
    - assets/icons/tab_group.svg
    - assets/icons/manage_accounts.svg
    - assets/images/placeholder.png
    - assets/icons/manage_accounts.svg
    - assets/json/clock_animation.json
    - assets/json/circle.json
    - assets/json/timer-001.json
    - assets/json/sound-ani.json
    - assets/json/loading_line.json
    - assets/json/no_connection.json
    - assets/json/robot.json
    - assets/json/robot2.json
    - assets/icons/kazanimlar.svg
    - assets/icons/green_check.svg
    - assets/icons/teste_basla.svg
    - assets/icons/cancel_test.svg
    - assets/icons/alarm.svg
    - assets/icons/chevron_left.svg
    - assets/icons/chevron_right.svg
    - assets/icons/Left.svg
    - assets/icons/Right.svg
    - assets/icons/ink_eraser.svg
    - assets/icons/stylus_note.svg
    - assets/icons/touch_app.svg
    - assets/icons/pause_circle.svg
    - assets/icons/play_circle.svg
    - assets/icons/stop_circle.svg
    - assets/icons/chart.svg
    - assets/icons/delete.svg
    - assets/icons/ios_share.svg
    - assets/icons/sendSimilarQuestion.svg
    - assets/icons/list.svg
    - assets/icons/test.svg
    - assets/icons/chart_data.svg
    - assets/icons/home_noti.svg
    - assets/icons/gain_ok.svg
    - assets/icons/gain_arrow.svg
    - assets/icons/correct_count.svg
    - assets/icons/incorrect_count.svg
    - assets/icons/homework_date.svg
    - assets/icons/homework_id.svg
    - assets/icons/homework_lesson.svg
    - assets/icons/homework_teacher.svg
    - assets/icons/pdf_download.svg
    - assets/icons/full_pdf.svg
    - assets/icons/homework_id.svg
    - assets/icons/homework_lesson.svg
    - assets/icons/homework_teacher.svg
    - assets/icons/homework_date.svg
    - assets/icons/close_fullscreen.svg
    - assets/icons/appbar_back.svg
    - assets/images/seduss_logo.png
    - assets/images/alt-yazi.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 900
        - asset: assets/fonts/Quicksand-Semibold.ttf
